### ISSUE TITLE
Reading declarations of undefined

### ISSUE THREAD

**Issue by EinfachLeo** [timocov/dts-bundle-generator#329]
**Bug report**

Hi! 

When I try to run the generator, I get an error
`Cannot read properties of undefined (reading 'declarations')`
(it happens both locally and in the [Github job](https://github.com/Hexafuchs/what.js/actions/runs/10167908927/job/28121292612))

I took the time to get the proper stacktrace, but I am none the wiser.
```typescript
TypeError: Cannot read properties of undefined (reading 'declarations')
    at getDeclarationsForSymbol ([...]/node_modules/dts-bundle-generator/dist/helpers/typescript.js:114:16)
    at TypesUsageEvaluator.computeUsageForNode ([...]/node_modules/dts-bundle-generator/dist/types-usage-evaluator.js:115:93)
    at visitNodes ([...]/node_modules/typescript/lib/typescript.js:31715:22)
    at forEachChildInSourceFile ([...]/node_modules/typescript/lib/typescript.js:31928:12)
    at Object.forEachChild ([...]/node_modules/typescript/lib/typescript.js:32228:35)
    at TypesUsageEvaluator.computeUsages ([...]/node_modules/dts-bundle-generator/dist/types-usage-evaluator.js:58:12)
    at new TypesUsageEvaluator ([...]/node_modules/dts-bundle-generator/dist/types-usage-evaluator.js:11:12)
    at generateDtsBundle ([...]/node_modules/dts-bundle-generator/dist/bundle-generator.js:20:31)
    at main ([...]/node_modules/dts-bundle-generator/dist/bin/dts-bundle-generator.js:193:67)
    at measureTime ([...]/node_modules/dts-bundle-generator/dist/helpers/measure-time.js:10:5)
```

**Additional context**
The entire command chain I ran is `rimraf build/**/* && tsc && vite build && dts-bundle-generator --config ./dts-bundle-generator.config.ts && copyfiles ./package.json build`. The config file looks like this:
```typescript
const config = {
  entries: [
    {
      filePath: './src/index.ts',
      outFile: './build/dist/index.d.ts',
      noCheck: false,
    },
  ],
};

module.exports = config;
```

**Comment by aryaemami59** [comment]
Having the exact same issue. Did you figure out a solution yet?

**Comment by timocov** [comment]
Can you share the repro for this issue?

**Comment by aryaemami59** [comment]
@timocov I'm pretty sure it was the `types` field in `tsconfig.json` that was causing the issue. Does your problem go away if you remove it or just set it to an empty array?

**Comment by timocov** [comment]
> Does your problem go away if you remove it or just set it to an empty array?

@aryaemami59 is this question for @EinfachLeo ?

**Comment by aryaemami59** [comment]
@timocov Yes my apologies.

**Comment by abc3660170** [comment]
Can you share the repro for this issue?

**Comment by EinfachLeo** [comment]
@aryaemami59 Seems to go away, yes
