### ISSUE TITLE
Error when using with axios 1.7.8

### ISSUE THREAD

**Issue by lpicchi** [timocov/dts-bundle-generator#339]
**Bug report**
I'm using `bundle-declarations-webpack-plugin` that uses this lib under the hood. After upgrading to axios 1.7.8 I got an error during types generation.

**Error**

```
LOG from BundleDeclarationsWebpackPlugin
<w> Failed to create .d.ts Error: Something went wrong - getSymbolsUsingSymbol returned null but expected to be a set of symbols (symbol=Cancel)
<w>     at getExportedSymbolsUsingSymbol (C:\Projects\comarb\comarb-bid-portal-api\node_modules\dts-bundle-generator\dist\bundle-generator.js:672:23)
<w>     at shouldSymbolBeImported (C:\Projects\comarb\comarb-bid-portal-api\node_modules\dts-bundle-generator\dist\bundle-generator.js:660:20)
<w>     at shouldNodeBeImported (C:\Projects\comarb\comarb-bid-portal-api\node_modules\dts-bundle-generator\dist\bundle-generator.js:636:20)
<w>     at forEachNodeThatShouldBeImported (C:\Projects\comarb\comarb-bid-portal-api\node_modules\dts-bundle-generator\dist\bundle-generator.js:376:21)
<w>     at updateImportsForStatement (C:\Projects\comarb\comarb-bid-portal-api\node_modules\dts-bundle-generator\dist\bundle-generator.js:382:13)
<w>     at updateResultImpl (C:\Projects\comarb\comarb-bid-portal-api\node_modules\dts-bundle-generator\dist\bundle-generator.js:130:29)
<w>     at updateResultForAnyModule (C:\Projects\comarb\comarb-bid-portal-api\node_modules\dts-bundle-generator\dist\bundle-generator.js:176:13)
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\dts-bundle-generator\dist\bundle-generator.js:871:13
<w>     at Array.map (<anonymous>)
<w>     at generateDtsBundle (C:\Projects\comarb\comarb-bid-portal-api\node_modules\dts-bundle-generator\dist\bundle-generator.js:22:20)
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\bundle-declarations-webpack-plugin\dist\index.cjs:1:978
<w>     at new Promise (<anonymous>)
<w>     at a (C:\Projects\comarb\comarb-bid-portal-api\node_modules\bundle-declarations-webpack-plugin\dist\index.cjs:1:925)
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\bundle-declarations-webpack-plugin\dist\index.cjs:1:2926
<w>     at fn (C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:537:19)
<w>     at Hook.eval [as callAsync] (eval at create (C:\Projects\comarb\comarb-bid-portal-api\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:67:17)
<w>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Projects\comarb\comarb-bid-portal-api\node_modules\tapable\lib\Hook.js:18:14)
<w>     at cont (C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:3072:34)
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:3120:10
<w>     at symbolIterator (C:\Projects\comarb\comarb-bid-portal-api\node_modules\neo-async\async.js:3485:9)
<w>     at done (C:\Projects\comarb\comarb-bid-portal-api\node_modules\neo-async\async.js:3527:9)
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\neo-async\async.js:2830:7
<w>     at Object.each (C:\Projects\comarb\comarb-bid-portal-api\node_modules\neo-async\async.js:2857:9)
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:4569:14
<w>     at symbolIterator (C:\Projects\comarb\comarb-bid-portal-api\node_modules\neo-async\async.js:3482:9)
<w>     at timesSync (C:\Projects\comarb\comarb-bid-portal-api\node_modules\neo-async\async.js:2297:7)
<w>     at Object.eachLimit (C:\Projects\comarb\comarb-bid-portal-api\node_modules\neo-async\async.js:3463:5)
<w>     at Compilation.createChunkAssets (C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:4546:12)
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:3115:14
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:3296:6
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\neo-async\async.js:2818:7
<w>     at done (C:\Projects\comarb\comarb-bid-portal-api\node_modules\neo-async\async.js:3522:9)
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:3259:8
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:3369:32
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\HookWebpackError.js:68:3
<w>     at Hook.eval [as callAsync] (eval at create (C:\Projects\comarb\comarb-bid-portal-api\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
<w>     at Cache.store (C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Cache.js:107:20)
<w>     at ItemCacheFacade.store (C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\CacheFacade.js:141:15)
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:3369:11
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Cache.js:93:5
<w>     at Hook.eval [as callAsync] (eval at create (C:\Projects\comarb\comarb-bid-portal-api\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
<w>     at Cache.get (C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Cache.js:75:18)
<w>     at ItemCacheFacade.get (C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\CacheFacade.js:115:15)
<w>     at Compilation._codeGenerationModule (C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:3338:9)
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:3245:11
<w>     at arrayIterator (C:\Projects\comarb\comarb-bid-portal-api\node_modules\neo-async\async.js:3467:9)
<w>     at done (C:\Projects\comarb\comarb-bid-portal-api\node_modules\neo-async\async.js:3527:9)
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:3259:8
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\Compilation.js:3369:32
<w>     at C:\Projects\comarb\comarb-bid-portal-api\node_modules\webpack\lib\HookWebpackError.js:68:3
+ 1 hidden lines
```

**Additional context**
I think this is related to this [change ](https://github.com/axios/axios/commit/c71811b00f2fcff558e4382ba913bdac4ad7200e) in Axios but really don't have the time to inspect it right now and my knowledge in the inner workings of this lib is really scarce.

NOTE: If anyone having this same error just downgrade `axios` to `1.7.7`

**Comment by timocov** [comment]
Are you able to reproduce the same issue without using that plugin? If so, is it possible to share a repro here?

**Comment by lpicchi** [comment]
Sure! 

https://github.com/lpicchi/dts-bundle-generator-axios-bug

Success with axios 1.7.7:

![image](https://github.com/user-attachments/assets/0b909c3f-6910-4751-b186-c08e1af89a80)

![image](https://github.com/user-attachments/assets/49b6d8aa-c32c-43ad-a439-4f2a8e2b53e7)


Error with axios 1.7.8:

![image](https://github.com/user-attachments/assets/0ec599b9-55ea-4c60-b67d-7db022258e14)

**Comment by thefat32** [comment]
This may have been an axios side typings ereror, works now in latest axios version
