### ISSUE TITLE
Can not be used when multiple nested aliases are involved

### ISSUE THREAD

**Issue by Gggpound** [timocov/dts-bundle-generator#341]
**Bug report**
When I use it in a monorepo project, I can not export the type correctly, and usually the result is a null value
**Input code**

```ts
export { debounce, get, merge, mergeWith, set } from 'lodash-es';
```

<img width="1419" alt="image" src="https://github.com/user-attachments/assets/36de293f-c635-4eff-8f79-d52eb2f13b80">

this `exportElementSymbol` is undefined, and throw an error.

**Comment by timocov** [comment]
@Gggpound what error are you getting in your codebase? I can reproduce an error `Error: Something went wrong - a symbol debounce for top-level identifier debounce cannot be renamed` but it seems it is not what you're getting?

**Comment by timocov** [comment]
@Gggpound any news?

**Comment by unanmed** [comment]
Hi, I’m encountering similar issue described here, and I’d like to provide more details that might help reproduce and diagnose the problem. Apologize for using AI to generate this comment, since my English is not very good.

### Project Structure & Context

I'm using `dts-bundle-generator` in a **monorepo** (using pnpm workspaces), and my issue occurs when trying to generate a bundled declaration file from a package (`A`) that depends on another internal workspace package (`B`).

### Key Info

1. **Package A** depends on **Package B** via workspace reference (`"@myorg/pkg-b": "workspace:*"`).
2. Each package uses an `index.ts` as the main entry point, and uses the pattern:
   ```ts
   export * from './module-a';
   export * from './module-b';
   ```
3. My codebase includes some **JSX/TSX files** using React.
4. I have set `followSymlinks` to false.
5. During `dts-bundle-generator` execution, I get a crash with the following stack trace:

### Error Stack

```
TypeError: Cannot read properties of undefined (reading 'declarations')
    at getDeclarationsForSymbol (E:\github\motajs-engine\node_modules\.pnpm\dts-bundle-generator@9.5.1\node_modules\dts-bundle-generator\dist\helpers\typescript.js:114:16)
    at TypesUsageEvaluator.computeUsageForNode (E:\github\motajs-engine\node_modules\.pnpm\dts-bundle-generator@9.5.1\node_modules\dts-bundle-generator\dist\types-usage-evaluator.js:115:93)
    at visitNodes (E:\github\motajs-engine\node_modules\.pnpm\typescript@5.8.3\node_modules\typescript\lib\typescript.js:32316:22)
    at forEachChildInSourceFile (E:\github\motajs-engine\node_modules\.pnpm\typescript@5.8.3\node_modules\typescript\lib\typescript.js:32529:12)
    at Object.forEachChild (E:\github\motajs-engine\node_modules\.pnpm\typescript@5.8.3\node_modules\typescript\lib\typescript.js:32829:35)
    at TypesUsageEvaluator.computeUsages (E:\github\motajs-engine\node_modules\.pnpm\dts-bundle-generator@9.5.1\node_modules\dts-bundle-generator\dist\types-usage-evaluator.js:58:16)
    at new TypesUsageEvaluator (E:\github\motajs-engine\node_modules\.pnpm\dts-bundle-generator@9.5.1\node_modules\dts-bundle-generator\dist\types-usage-evaluator.js:11:14)
    at generateDtsBundle (E:\github\motajs-engine\node_modules\.pnpm\dts-bundle-generator@9.5.1\node_modules\dts-bundle-generator\dist\bundle-generator.js:20:33)
    at buildPackages (E:\github\motajs-engine\scripts\build-lib.ts:64:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

![Image](https://github.com/user-attachments/assets/a96ede1b-c531-4c5b-a63b-e80b6a21a30b)

Thanks for this awesome tool — happy to help if needed!

**Comment by gtbuchanan** [comment]
I just encountered this problem as well. [Here's a minimal reproduction](https://github.com/gtbuchanan/dts-bundle-generator-repro-341).
