### ISSUE TITLE
 undefined is not an object (evaluating 'symbol.declarations')

### ISSUE THREAD

**Issue by SamHoque** [timocov/dts-bundle-generator#345]
```
 bun run build.ts
109 |     return ts.isModuleDeclaration(statement) && isGlobalScopeAugmentation(statement);
110 | }
111 | exports.isDeclareGlobalStatement = isDeclareGlobalStatement;
112 | function getDeclarationsForSymbol(symbol) {
113 |     const result = [];
114 |     if (symbol.declarations !== undefined) {
              ^
TypeError: undefined is not an object (evaluating 'symbol.declarations')
      at getDeclarationsForSymbol (C:\Workspace\lynx-proxy\bun-lib-starter\node_modules\dts-bundle-generator\dist\helpers\typescript.js:114:9)
      at computeUsageForNode (C:\Workspace\lynx-proxy\bun-lib-starter\node_modules\dts-bundle-generator\dist\types-usage-evaluator.js:115:68)
      at visitNodes (C:\Workspace\lynx-proxy\bun-lib-starter\node_modules\typescript\lib\typescript.js:27934:24)
      at forEachChildInSourceFile (C:\Workspace\lynx-proxy\bun-lib-starter\node_modules\typescript\lib\typescript.js:28556:18)
      at computeUsages (C:\Workspace\lynx-proxy\bun-lib-starter\node_modules\dts-bundle-generator\dist\types-usage-evaluator.js:58:16)
      at new TypesUsageEvaluator (C:\Workspace\lynx-proxy\bun-lib-starter\node_modules\dts-bundle-generator\dist\types-usage-evaluator.js:11:14)
      at generateDtsBundle (C:\Workspace\lynx-proxy\bun-lib-starter\node_modules\dts-bundle-generator\dist\bundle-generator.js:20:33)
      at C:\Workspace\lynx-proxy\bun-lib-starter\node_modules\bun-plugin-dts\dist\index.js:1:1205
      at setup (C:\Workspace\lynx-proxy\bun-lib-starter\node_modules\bun-plugin-dts\dist\index.js:1:1050)
      at C:\Workspace\lynx-proxy\bun-lib-starter\build.ts:3:11

Bun v1.1.42 (Windows x64)
error: script "build" exited with code 1
```

build.ts:
```
import dts from 'bun-plugin-dts'

await Bun.build({
    entrypoints: [ './src/module.ts'],
    outdir: './dist',
    plugins: [dts()],
    root: './src',
    minify: true,
    target: "browser",
    external: ['*']
})
```

module.ts

```
import 'wxt';
import { defineWxtModule } from 'wxt/modules';

export default defineWxtModule({
    name: 'x',
    configKey: 'xxx',

    setup(wxt, options = {}) {},
});
```

**Comment by timocov** [comment]
First of all, I don't know how exactly `bun-plugin-dts` works and what it does internally in contrast with CLI this tool provides.

Second, when I try to reproduce the issue with CLI, I'm getting the following output:

```
$ cat src/test.ts
import 'wxt';
import { defineWxtModule } from 'wxt/modules';

export default defineWxtModule({
    name: 'x',
    configKey: 'xxx',

    setup(wxt, options = {}) {},
});

$ ./node_modules/.bin/dts-bundle-generator src/test.ts
Compiling input files...
node_modules/unimport/dist/index.d.ts(8,1): error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

Error: Compiled with errors
```

And if I check `node_modules/unimport/dist/index.d.ts` it contains `const version = "3.14.5";` line which is clearly a wrong syntax for a dts file, it must be `declare const version` instead.

Thus, please either provide a better reproduction that it related to this tool (without other tools involved) or cut tickets to appropriate projects.

**Comment by arshad-yaseen** [comment]
Same happening for me
